CXX           = g++
DEFINES       = -O3 -Wall -ffast-math -pthread
CXXFLAGS      = -march=armv6 -mfloat-abi=hard $(DEFINES)
INCPATH       = -I.
LINKLIBS      = -lm -lpthread
STRIP         = strip
AR            = ar rcs
DEL           = rm -rf
MKDIR         = mkdir -p
FORMAT        = astyle -A1
TAR           = tar
COMPRESS      = gzip -9f
