CXX           = g++
DEFINES       = -DNB_THREAD=$(NB_THREAD)
CXXFLAGS      = -m32 -mtune=native -march=native -malign-double -O3 -Wall -ffast-math -pthread $(DEFINES)
INCDIR        = -I.
LINKLIBS      = -lm -lpthread
STRIP         = strip
AR            = ar rcs
DEL           = rm -rf
MKDIR         = mkdir -p
FORMAT        = astyle -A1
TAR           = tar
COMPRESS      = gzip -9f
NPROC         = nproc
