CXX           = g++
DEFINES       = -O3 -Wall -ffast-math -pthread
CXXFLAGS      = -m32 -mtune=native -march=native -malign-double $(DEFINES)
INCDIR        = -I.
LINKLIBS      = -lm -lpthread
STRIP         = strip
AR            = ar rcs
DEL           = rm -rf
MKDIR         = mkdir -p
FORMAT        = astyle -A1
TAR           = tar
COMPRESS      = gzip -9f
