CXX           = g++
DEFINES       = -DNB_THREAD=$(NB_THREAD)
CXXFLAGS      = -m64 -mtune=970 -O3 -Wall -ffast-math -pthread $(DEFINES)
INCDIR        = -I.
LINKLIBS      = -lstdc++ -lm -lpthread
STRIP         = strip
AR            = ar rcs
DEL           = rm -rf
MKDIR         = mkdir -p
FORMAT        = astyle -A1
TAR           = tar
COMPRESS      = gzip -9f
