CXX           = g++
DEFINES       = -O3 -Wall -ffast-math -pthread
CXXFLAGS      = -m64 -mtune=native -march=native $(DEFINES)
INCPATH       = -I.
LINKLIBS      = -L/usr/lib/x86_64-linux-gnu -lm -lpthread -Wl,-rpath -Wl,/usr/lib/x86_64-linux-gnu
STRIP         = strip
AR            = ar rcs
DEL           = rm -rf
MKDIR         = mkdir -p
FORMAT        = astyle -A1
TAR           = tar
COMPRESS      = gzip -9f
